baseURL = "https://mlb.tomhummel.com"
languageCode = "en-us"
title = "Tom Hummel :: Baseball Blog"

[taxonomies]
  tag = "tags"

[params]
    Title = "Tom Hummel's baseball blog"
    site_description = "Baseball analysis, software, and writing"
    twitter_handle = "tphummelmlb"
    github_repo = "https://github.com/tphummel/mlb.tomhummel.com"
    # facebook_handle =
    # instagram_handle =

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1