baseURL = "https://mlb.tomhummel.com"
languageCode = "en-us"
title = "Tom Hummel :: Baseball Blog"

[taxonomies]
  tag = "tags"

[params]
    Title = "Tom Hummel's Baseball Blog"
    site_description = "Baseball analysis, software, and writing."
    github_repo = "https://github.com/tphummel/mlb.tomhummel.com"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1